<?php

namespace App\Providers\Faker;

use Faker\Provider\Base;

class CustomFakerProvider extends Base
{
    public function streetPrefixes()
    {
        $street_prefixes = [
            "Ampliación",
            "Andador",
            "Avenida",
            "Boulevard",
            "Calle",
            "Callejón",
            "Calzada",
            "Cerrada",
            "Circuito",
            "Corredor",
            "Eje vial",
            "Pasaje",
            "Periférico",
            "Privada",
            "Prolongación",
            "Viaducto",
        ];

        return $street_prefixes[rand(0, count($street_prefixes) - 1)];
    }
    public function neighborhood()
    {
        $neighborhoods = [
            "Aguilera",
            "Aldana",
            "Amp. Cosmopolita",
            "Amp. del Gas",
            "Amp. Petrolera",
            "Amp. San Pedro Xalpa",
            "Ángel Zimbrón",
            "Arenal",
            "Barrio de Huautla de Las Salinas",
            "Barrio San Andrés",
            "Barrio San Sebastián",
            "Centro de Azcapotzalco",
            "Clavería",
            "Coltongo",
            "Cosmopolita",
            "El Jagüey",
            "Estación Pantaco",
            "Ferrería",
            "Hacienda del Rosario",
            "Hogar y Seguridad",
            "Ignacio Allende",
            "Industrial Vallejo",
            "Jardín Azpeitia",
            "La Preciosa",
            "La Raza",
            "Las Salinas",
            "Liberación",
            "Libertad",
            "Los Reyes",
            "Monte Alto",
            "Nextengo",
            "Nueva España",
            "Nuevo Rosario",
            "Nuevo San Rafael",
            "Nuevo Santa Maria",
            "Obrero Popular",
            "Panteón San Isidro",
            "Pasteros",
            "Petrolera",
            "Plenitud",
            "Porvenir",
            "Potrero del Llano",
            "Prados del Rosario",
            "Pro Hogar",
            "Providencia",
            "Pueblo Quieto",
            "Pueblo San Andres de las Salinas",
            "Pueblo Santa Bárbara",
            "Pueblo Santa María Malinalco",
            "San Álvaro",
            "San Antonio",
            "San Bernabé",
        ];

        return $neighborhoods[rand(0, count($neighborhoods) - 1)];
    }

    public function city()
    {
        $cities = [
            "Ciudad de México",
            "Iztapalapa",
            "Ecatepec de Morelos",
            "Guadalajara",
            "Puebla",
            "Ciudad Juárez",
            "Tijuana",
            "León de los Aldama",
            "Gustavo Adolfo Madero",
            "Zapopan",
            "Monterrey",
            "Ciudad Nezahualcóyotl",
            "Chihuahua",
            "Naucalpan de Juárez",
            "Merida",
            "Alvaro Obregon",
            "San Luis Potosi",
            "Aguascalientes",
            "Hermosillo",
            "Saltillo",
            "Mexicali",
            "Culiacan",
            "Guadalupe",
            "Acapulco de Juarez",
            "Tlalnepantla",
            "Cancun",
            "Santiago de Queretaro",
            "Coyoacan",
            "Santa Maria Chimalhuacan",
            "Torreon",
            "Morelia",
            "Reynosa",
            "Tlaquepaque",
            "Tlalpan",
            "Tuxtla",
            "Cuauhtemoc",
            "Victoria de Durango",
            "Toluca",
            "Ciudad Lopez Mateos",
            "Cuautitlan Izcalli",
            "Ciudad Apodaca",
            "Heroica Matamoros",
            "San Nicolás de los Garza",
            "Venustiano Carranza",
            "Veracruz",
            "Xalapa de Enríquez",
            "Azcapotzalco",
            "Tonala",
            "Xochimilco",
            "Benito Juarez",
            "Iztacalco",
            "Mazatlan",
            "Irapuato",
            "Nuevo Laredo",
            "Miguel Hidalgo",
            "Xico",
            "Benito Juarez",
            "Villahermosa",
            "Ciudad General Escobedo",
            "Celaya",
            "Cuernavaca",
            "Tepic",
            "Ixtapaluca",
            "Tampico",
            "Ciudad Victoria",
            "Tlahuac",
            "Ciudad Obregón",
            "Nicolas Romero",
            "Ensenada",
            "Coacalco",
            "Santa Catarina",
            "Uruapan",
            "Gomez Palacio",
            "Los Mochis",
            "Pachuca de Soto",
            "Oaxaca",
            "Soledad de Graciano Sanchez",
            "Colonia del Valle",
            "Tehuacan",
            "Ojo de Agua",
            "Magdalena Contreras",
            "Coatzacoalcos",
            "Campeche",
            "Monclova",
            "La Paz",
            "Nogales",
            "Buenavista",
            "Puerto Vallarta",
            "Tapachula",
            "Ciudad Madero",
            "Chilpancingo",
            "Poza Rica de Hidalgo",
            "Chicoloapan",
            "Ciudad del Carmen",
            "Chalco",
            "Jiutepec",
            "Delegación Cuajimalpa de Morelos",
            "Salamanca",
            "San Luis Rio Colorado",
            "San Cristóbal de las Casas",
            "San Pablo de las Salinas",
            "Cuautla",
            "Ciudad Benito Juarez",
            "Chetumal",
            "Piedras Negras",
            "Playa del Carmen",
            "Zamora",
            "Cordoba",
            "San Juan del Rio",
            "Colima",
            "Ciudad Acuna",
            "Manzanillo",
            "Zacatecas",
            "Huixquilucan",
            "Ciudad Valles",
            "Guadalupe",
            "San Pedro Garza Garcia",
            "Fresnillo",
            "Orizaba",
            "Miramar",
            "Iguala de la Independencia",
            "Ciudad Delicias",
            "Ciudad de Villa de Alvarez",
            "Cuauhtemoc",
            "Navojoa",
            "Heroica Guaymas",
            "Minatitlan",
            "Cuautitlan",
            "Texcoco de Mora",
            "Parral",
            "Tepexpan",
            "Tulancingo",
            "Tuxtepec",
            "Colonia Lindavista",
            "Apatzingan",
            "Lagos de Moreno",
            "Temixco",
            "Ciudad Guzman",
            "Comitan",
            "Ciudad Río Bravo",
            "Garcia",
            "Tepatitlan de Morelos",
            "Cardenas",
            "Cholula",
            "Hacienda Santa Fe",
            "Atlixco",
            "Tecoman",
            "Los Reyes Acaquilpan",
            "Ciudad Mante",
            "Tuxpam de Rodriguez Cano",
            "Tlaxcala",
            "Heroica Zitacuaro",
            "Ocotlan",
            "La Piedad",
            "Ciudad Lerdo",
            "Ciudad Lazaro Cardenas",
            "Matehuala",
            "Agua Prieta",
            "Kanasin",
            "Cozumel",
            "Amozoc de Mota",
            "Salina Cruz",
            "San Martin Texmelucan de Labastida",
            "Juchitán de Zaragoza",
            "Silao",
            "Fuentes del Valle",
            "Guanajuato",
            "El Pueblito",
            "Guasave",
            "San Francisco del Rincón",
            "San Miguel de Allende",
            "San Jose del Cabo",
            "Frontera",
            "Cabo San Lucas",
            "Cadereyta Jimenez",
            "Valle de Santiago",
            "Cadereyta",
            "San Mateo Atenco",
            "Montemorelos",
            "Ixtapa-Zihuatanejo",
            "Santa Cruz Xoxocotlan",
            "Ramos Arizpe",
            "Tultepec",
            "Rosarito",
            "Tecate",
            "Sahuayo de Morelos",
            "Guamuchil",
            "Linares",
            "Tesistan",
            "San Andres Tuxtla",
            "Cortazar",
            "San Salvador Tizatlalli",
            "Ciudad Hidalgo",
            "Martinez de la Torre",
            "Villa Vicente Guerrero",
            "Colonia Nativitas",
            "Heroica Caborca",
            "Altamira",
            "Teziutlan",
            "Acambaro",
            "Jacona de Plancarte",
            "Puerto Penasco",
            "Huauchinango",
            "Nuevo Casas Grandes",
            "Pátzcuaro",
            "Sabinas",
            "San Bernardino Tlaxcalancingo",
            "Zinacantepec",
            "Santiago Teyahualco",
            "Coatepec",
            "Rioverde",
            "Ciudad de Huajuapan de León",
            "Zacapu",
            "Matamoros",
            "Taxco de Alarcón",
            "Arandas",
            "Huamantla",
            "Uriangato",
            "Teoloyucan",
            "Acayucan",
            "Zumpango",
            "Zacapu",
            "Polanco",
            "San Luis de la Paz",
            "Apizaco",
            "Emiliano Zapata",
            "Valladolid",
            "Valle Hermoso",
            "San Pedro",
            "San Juan de los Lagos",
            "Colonia del Sol",
            "Santa Ana Chiautempan",
            "Tierra Blanca",
            "Tlapa de Comonfort",
            "Tizimin",
            "Autlan de Navarro",
            "Chiapa de Corzo",
            "San Buenaventura",
            "Purisima de Bustos",
            "Tizayuca",
            "Moroleon",
            "Jerez de Garcia Salinas",
            "Jesus Maria",
            "Palenque",
            "Izucar de Matamoros",
            "Yautepec",
            "Las Choapas",
            "Empalme",
            "Cintalapa de Figueroa",
            "Juventino Rosas",
            "Santo Domingo Tehuantepec",
            "Ocosingo",
            "Comalcalco",
            "San Pedro",
            "Ciudad Constitución",
            "Panuco",
            "Rio Blanco",
            "Camargo",
            "Penjamo",
            "Huejutla de Reyes",
            "San Andres Cholula",
            "Xicotepec de Juarez",
            "Uman",
            "Los Reyes de Salgado",
            "Ocozocoautla de Espinosa",
            "Esperanza",
            "Melchor Ocampo",
            "Zacatelco",
            "Nueva Rosita",
            "Tepotzotlan",
            "Guacamayas",
            "Perote",
            "Progreso",
            "Villaflores",
            "Salvatierra",
            "Santa Teresa",
            "Santiago",
            "San Jerónimo Cuatro Vientos",
            "Ameca",
            "Agua Dulce",
            "Xalisco",
            "Coyotepec",
            "Ciudad Mendoza",
            "Tala",
            "San Martin Azcatepec",
            "Tlapacoyan",
            "Tonala",
            "La Barca",
            "San Pablo Autopan",
            "Ciudad Melchor Muzquiz",
            "Ixmiquilpan",
            "Fraccionamiento Real Palmas",
            "San Miguel Topilejo",
            "Maravatio de Ocampo",
            "Jose Mariano Jimenez",
            "Porticos de San Antonio",
            "Tepeji del Río de Ocampo",
            "Coatzintla",
            "Parras de la Fuente",
            "San Isidro",
            "Zacatlan",
            "Calpulalpan",
            "Ciudad Sabinas Hidalgo",
            "Rio Grande",
            "Ticul",
            "Jáltipan de Morelos",
            "Victor Rosales",
            "Tenosique",
            "Nueva Italia de Ruiz",
            "Zapotlanejo",
            "Macuspana",
            "Centro Familiar la Soledad",
            "Huixtla",
            "Ciudad Fernandez",
            "Amecameca",
            "Cananea",
            "Loma Bonita",
            "Huatusco",
            "San José Guadalupe Otzacatipan",
            "Chilapa de Alvarez",
            "Jimenez",
            "Champoton",
            "Miguel Aleman (La Doce)",
            "Escuinapa",
            "Tantoyuca",
            "Cosamaloapan",
            "Puruandiro",
            "Huatabampo",
            "Nicolás R Casillas",
            "Tlajomulco de Zuniga",
            "Tequisquiapan",
            "San Miguel Ajusco",
            "Coyula",
            "Pinotepa Nacional",
            "Escarcega",
            "Marfil",
            "Santa Isabel",
            "Actopan",
            "Tequila",
            "San Fernando",
            "Navolato",
            "Ixtapa",
            "Tecamachalco",
            "Pabellon de Arteaga",
            "Tula de Allende",
            "Ciudad Sahagun",
            "San Felipe",
            "Metepec",
            "San Sebastián el Grande",
            "Nuevo México",
            "Berriozabal",
            "Ajalpan",
            "Tultitlán de Mariano Escobedo",
            "Apaseo el Alto",
            "Rincon de Romos",
            "San Francisco Acuautla",
            "Sanctorum",
            "Catemaco",
            "Contla",
            "Leyva Solano",
            "Tuxpan",
            "Tepeaca",
            "Abasolo",
            "Huimanguillo",
            "Moyotzingo",
            "Villagran",
            "Atotonilco el Alto",
            "Rancho La Gloria",
            "Misantla",
            "Sayula",
            "Apan",
            "Francisco I. Madero",
            "Magdalena de Kino",
            "Teapa",
            "Las Pintitas",
            "Rio de Teapa",
            "Magdalena Atlicpac",
            "Isla",
            "San Jerónimo",
            "Reforma",
            "Ixtaczoquitlan",
            "Apaseo el Grande",
            "Santiago Papasquiaro",
            "Ciudad de Allende",
            "Ocoyoacac",
            "Puerto Escondido",
            "Acatzingo",
            "Tecax",
            "Felipe Carrillo Puerto",
            "Valente Diaz",
            "Huejotzingo",
            "Tacambaro de Codallos",
            "Tejupilco de Hidalgo",
            "Valle de Bravo",
            "Mixquiahuala de Juarez",
            "Ixtepec",
            "Emiliano Zapata"
        ];
 
        return $cities[rand(0, count($cities) - 1)];
    }
}
